### ISSUE TITLE
run_query() creates connection/session per each call

### ISSUE THREAD

**Issue by hotmori** [c4s4/sqlplus_commando#1]
It seems that using subprocess.Popen and session.communicate() leads to reconnect each time when single sql command run. At least it's not optimal and that's way it's impossible to use sql_commando in multi thread manner.

**Comment by c4s4** [comment]
This is by design: _sqlplus_commando_ performs requests calling _sqlplus_ on the command line. Thus each query creates a new connection.

**Comment by hotmori** [comment]
Well. It's ok when you've one huge sqlscript, that consits of other sqlscripts -- so one connect per this call looks reasonable, but it's only single case. More common (and flexible) case is when you connect to db only once and run sqlcommand using this connection -- there we can use Python to construct some logic.
Anyway, do you have some techical limitation for doing this? Looks like they are: deadlock of stdin writing and stdout reading. In my little test I've found some workaround but with limitations, i.e. I write ony one line to stdin and then reading one line from stdout, connection remains open.
